/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Player;
import java.awt.Color;

/**
 *
 * @author MDA 174321 :)
 */
public class BinaryChoicePromptComponent extends javax.swing.JPanel {
    static Color activeBgColor = new Color(100, 100, 100);
    static Color inactiveBgColor = new Color(200, 200, 200);
    PlayerController myController;
    boolean myIsBet;
    /**
     * Creates new form PlayerInputDoRoundChoiceComp
     */
    public BinaryChoicePromptComponent() {
        initComponents();
    }
    
    public void set(String aChoiceText, String aYesButtonText, String aNoButtonText, boolean aIsBet, PlayerController aController){
        myController = aController;
        myChoiceLabel.setText(aChoiceText);
        myYesBtn.setText(aYesButtonText);
        myNoBtn.setText(aNoButtonText);
        myIsBet = aIsBet;
    }
    
    public void setInactive(){
        this.setBackground(inactiveBgColor);
        myYesBtn.setEnabled(false);
        myNoBtn.setEnabled(false);
    }
    
    public void setActive(){
        this.setBackground(activeBgColor);
        myYesBtn.setEnabled(true);
        myNoBtn.setEnabled(true);
    }
    
    public void myYesPressed(){
        if(myIsBet){
            myController.playerCalls();
        }else{
            myController.playerWantsToContinueGame();
        }
    }
    
    public void myNoPressed(){
        if(myIsBet){
            myController.playerPassSecond();
        }else{
            myController.playerWantsToLeaveTheGame();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myChoiceLabel = new javax.swing.JLabel();
        myYesBtn = new javax.swing.JButton();
        myNoBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(100, 100, 100));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(170, 93));

        myChoiceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myChoiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        myChoiceLabel.setText("Otra ronda?");

        myYesBtn.setText("Si");
        myYesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myYesBtnActionPerformed(evt);
            }
        });

        myNoBtn.setText("No");
        myNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myChoiceLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(myNoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myChoiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myYesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myYesBtnActionPerformed
        myYesPressed();
    }//GEN-LAST:event_myYesBtnActionPerformed

    private void myNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNoBtnActionPerformed
        myNoPressed();
    }//GEN-LAST:event_myNoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myChoiceLabel;
    private javax.swing.JButton myNoBtn;
    private javax.swing.JButton myYesBtn;
    // End of variables declaration//GEN-END:variables
}
