/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Player;

import java.util.ArrayList;
import poker.Utils;

/**
 *
 * @author MDA 174321 :)
 */
public class HandComponent extends javax.swing.JPanel {

    ArrayList<CardComponent> myCards = new ArrayList();
    boolean myInited = false;
    
    public HandComponent() {
        initComponents();
        
        myCards.add(cardComponent1);
        myCards.add(cardComponent2);
        myCards.add(cardComponent3);
        myCards.add(cardComponent4);
        myCards.add(cardComponent5);
        myInited = true;
    }
    
    public void setHand(ArrayList<CardModel> aCards){
        if(!myInited || aCards == null || aCards.size() != myCards.size()){
            Utils.logState("Setup error on HandComponent, how did we get here?");
            return;
        }
            
        for (int i= 0; i < myCards.size(); i++){
            myCards.get(i).setCardFront(aCards.get(i).myCardSuitEnum, aCards.get(i).myCardOrderEnum);
        }
    }
    
    public void setCardsReverse(){
        for (CardComponent c: myCards){
            c.setCardReverse();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardComponent1 = new poker.UI.Player.CardComponent();
        cardComponent2 = new poker.UI.Player.CardComponent();
        cardComponent3 = new poker.UI.Player.CardComponent();
        cardComponent4 = new poker.UI.Player.CardComponent();
        cardComponent5 = new poker.UI.Player.CardComponent();

        setBackground(new java.awt.Color(100, 100, 100));

        javax.swing.GroupLayout cardComponent1Layout = new javax.swing.GroupLayout(cardComponent1);
        cardComponent1.setLayout(cardComponent1Layout);
        cardComponent1Layout.setHorizontalGroup(
            cardComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        cardComponent1Layout.setVerticalGroup(
            cardComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardComponent2Layout = new javax.swing.GroupLayout(cardComponent2);
        cardComponent2.setLayout(cardComponent2Layout);
        cardComponent2Layout.setHorizontalGroup(
            cardComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        cardComponent2Layout.setVerticalGroup(
            cardComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardComponent3Layout = new javax.swing.GroupLayout(cardComponent3);
        cardComponent3.setLayout(cardComponent3Layout);
        cardComponent3Layout.setHorizontalGroup(
            cardComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        cardComponent3Layout.setVerticalGroup(
            cardComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardComponent4Layout = new javax.swing.GroupLayout(cardComponent4);
        cardComponent4.setLayout(cardComponent4Layout);
        cardComponent4Layout.setHorizontalGroup(
            cardComponent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        cardComponent4Layout.setVerticalGroup(
            cardComponent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardComponent5Layout = new javax.swing.GroupLayout(cardComponent5);
        cardComponent5.setLayout(cardComponent5Layout);
        cardComponent5Layout.setHorizontalGroup(
            cardComponent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        cardComponent5Layout.setVerticalGroup(
            cardComponent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardComponent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardComponent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardComponent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardComponent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardComponent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardComponent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private poker.UI.Player.CardComponent cardComponent1;
    private poker.UI.Player.CardComponent cardComponent2;
    private poker.UI.Player.CardComponent cardComponent3;
    private poker.UI.Player.CardComponent cardComponent4;
    private poker.UI.Player.CardComponent cardComponent5;
    // End of variables declaration//GEN-END:variables
}
