/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Player;

/**
 *
 * @author MDA 174321 :)
 */
public class PlayerInfoComponent extends javax.swing.JPanel {

    public PlayerInfoComponent() {
        initComponents();
    }
    
    public void set(PlayerInfoModel aPlayerInfo){
        if(aPlayerInfo.myIsLocal){
            setDataLocal(aPlayerInfo.myName, aPlayerInfo.myState, aPlayerInfo.myFunds, aPlayerInfo.myPattern);
        }else{
            setDataRemote(aPlayerInfo.myName, aPlayerInfo.myState);
            hideFundsAndPattern();
        }
    }
    
    private void setDataLocal(String aName, String aState, String aFunds, String aPattern){
        myNameField.setText(aName);
        myStateField.setText(aState);
        myFundsField.setText(aFunds);
        myPatternField.setText(aPattern);        
    }
    
    private void setDataRemote(String aName, String aState){
        myNameField.setText(aName);
        myStateField.setText(aState);
    }
    
    private void hideFundsAndPattern(){
        myFundsLabel.setVisible(false);
        myPatternLabel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myNameLabel = new javax.swing.JLabel();
        myStateLabel = new javax.swing.JLabel();
        myFundsLabel = new javax.swing.JLabel();
        myPatternLabel = new javax.swing.JLabel();
        myNameField = new javax.swing.JTextField();
        myStateField = new javax.swing.JTextField();
        myFundsField = new javax.swing.JTextField();
        myPatternField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(100, 100, 100));

        myNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        myNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        myNameLabel.setText("Nombre:");

        myStateLabel.setForeground(new java.awt.Color(255, 255, 255));
        myStateLabel.setText("Estado:");

        myFundsLabel.setBackground(new java.awt.Color(255, 255, 255));
        myFundsLabel.setForeground(new java.awt.Color(255, 255, 255));
        myFundsLabel.setText("Saldo:");

        myPatternLabel.setForeground(new java.awt.Color(255, 255, 255));
        myPatternLabel.setText("Figura:");

        myNameField.setEditable(false);
        myNameField.setText("Un nombre");
        myNameField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        myNameField.setEnabled(false);
        myNameField.setFocusable(false);

        myStateField.setEditable(false);
        myStateField.setText("Un estado");
        myStateField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        myStateField.setEnabled(false);
        myStateField.setFocusable(false);
        myStateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myStateFieldActionPerformed(evt);
            }
        });

        myFundsField.setEditable(false);
        myFundsField.setText("10");
        myFundsField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        myFundsField.setEnabled(false);
        myFundsField.setFocusable(false);

        myPatternField.setEditable(false);
        myPatternField.setText("Una Figura");
        myPatternField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        myPatternField.setDoubleBuffered(true);
        myPatternField.setEnabled(false);
        myPatternField.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myStateLabel)
                        .addGap(8, 8, 8)
                        .addComponent(myStateField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myFundsLabel)
                            .addComponent(myPatternLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myPatternField)
                            .addComponent(myFundsField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myNameLabel)
                    .addComponent(myNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myStateLabel)
                    .addComponent(myStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myFundsLabel)
                    .addComponent(myFundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myPatternLabel)
                    .addComponent(myPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myStateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myStateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myStateFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField myFundsField;
    private javax.swing.JLabel myFundsLabel;
    private javax.swing.JTextField myNameField;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JTextField myPatternField;
    private javax.swing.JLabel myPatternLabel;
    private javax.swing.JTextField myStateField;
    private javax.swing.JLabel myStateLabel;
    // End of variables declaration//GEN-END:variables
}
