/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Player;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author MDA 174321 :)
 */
public class PlayerInfoComponent extends javax.swing.JPanel {
    static Color transparentWhite = new Color(255, 255, 255, 0);
    static Color opaqueWhite = new Color(255, 255, 255, 255);
    ArrayList<javax.swing.JLabel> myLabels = new ArrayList();
    
    public PlayerInfoComponent() {
        initComponents();
        
        myLabels.add(myFundsLabel);
        myLabels.add(myFundsTextLabel);
        myLabels.add(myNameLabel);
        myLabels.add(myNameTextLabel);
        myLabels.add(myPatternLabel);
        myLabels.add(myPatternTextLabel);
        myLabels.add(myStateLabel);
        myLabels.add(myStateTextLabel);
    }
    
    public void set(PlayerModel aPlayerModel){
        if(aPlayerModel.myIsLocal){
            String funds = Integer.toString(aPlayerModel.myFunds);
            setDataLocal(aPlayerModel.getFullName(), aPlayerModel.myState, funds, aPlayerModel.myPattern);
        }else{
            hideFundsAndPattern();
            setDataRemote(aPlayerModel.getFullName(), aPlayerModel.myState);
        }
    }
    
    private void setDataLocal(String aName, String aState, String aFunds, String aPattern){
        myNameTextLabel.setText(aName);
        myStateTextLabel.setText(aState);
        myFundsTextLabel.setText(aFunds);
        myPatternTextLabel.setText(aPattern);        
    }
    
    private void setDataRemote(String aName, String aState){
        myNameTextLabel.setText(aName);
        myStateTextLabel.setText(aState);
    }
    
    public void showInfo(boolean aShow){
        for (javax.swing.JLabel label: myLabels){
            if(aShow)
                label.setForeground(opaqueWhite);
            else
                label.setForeground(transparentWhite);
        }
    }
    
    private void hideFundsAndPattern(){
        myFundsLabel.setVisible(false);
        myFundsTextLabel.setVisible(false);
        myPatternLabel.setVisible(false);
        myPatternTextLabel.setVisible(false);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myNameLabel = new javax.swing.JLabel();
        myStateLabel = new javax.swing.JLabel();
        myFundsLabel = new javax.swing.JLabel();
        myPatternLabel = new javax.swing.JLabel();
        myNameTextLabel = new javax.swing.JLabel();
        myStateTextLabel = new javax.swing.JLabel();
        myFundsTextLabel = new javax.swing.JLabel();
        myPatternTextLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(100, 100, 100));

        myNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        myNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        myNameLabel.setText("Nombre:");

        myStateLabel.setForeground(new java.awt.Color(255, 255, 255));
        myStateLabel.setText("Estado:");

        myFundsLabel.setBackground(new java.awt.Color(255, 255, 255));
        myFundsLabel.setForeground(new java.awt.Color(255, 255, 255));
        myFundsLabel.setText("Saldo:");

        myPatternLabel.setForeground(new java.awt.Color(255, 255, 255));
        myPatternLabel.setText("Figura:");

        myNameTextLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        myNameTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        myNameTextLabel.setText("Un Nombre");
        myNameTextLabel.setMaximumSize(new java.awt.Dimension(103, 14));
        myNameTextLabel.setMinimumSize(new java.awt.Dimension(103, 14));
        myNameTextLabel.setPreferredSize(new java.awt.Dimension(103, 14));

        myStateTextLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        myStateTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        myStateTextLabel.setText("Un Estado");
        myStateTextLabel.setMaximumSize(new java.awt.Dimension(103, 14));
        myStateTextLabel.setMinimumSize(new java.awt.Dimension(103, 14));
        myStateTextLabel.setPreferredSize(new java.awt.Dimension(103, 14));

        myFundsTextLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        myFundsTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        myFundsTextLabel.setText("Un Saldo");
        myFundsTextLabel.setMaximumSize(new java.awt.Dimension(103, 14));
        myFundsTextLabel.setMinimumSize(new java.awt.Dimension(103, 14));
        myFundsTextLabel.setPreferredSize(new java.awt.Dimension(103, 14));

        myPatternTextLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        myPatternTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        myPatternTextLabel.setText("Una Figura");
        myPatternTextLabel.setMaximumSize(new java.awt.Dimension(103, 14));
        myPatternTextLabel.setMinimumSize(new java.awt.Dimension(103, 14));
        myPatternTextLabel.setPreferredSize(new java.awt.Dimension(103, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myNameTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myStateLabel)
                            .addComponent(myFundsLabel)
                            .addComponent(myPatternLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myPatternTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myFundsTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myStateTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myNameLabel)
                    .addComponent(myNameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myStateLabel)
                    .addComponent(myStateTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myFundsLabel)
                    .addComponent(myFundsTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myPatternLabel)
                    .addComponent(myPatternTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myFundsLabel;
    private javax.swing.JLabel myFundsTextLabel;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JLabel myNameTextLabel;
    private javax.swing.JLabel myPatternLabel;
    private javax.swing.JLabel myPatternTextLabel;
    private javax.swing.JLabel myStateLabel;
    private javax.swing.JLabel myStateTextLabel;
    // End of variables declaration//GEN-END:variables
}
