/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Player;
import java.awt.Color;

/**
 *
 * @author MDA 174321 :)
 */
public class PlayerInputDoBetFieldComp extends javax.swing.JPanel {
    static Color activeBgColor = new Color(100, 100, 100);
    static Color inactiveBgColor = new Color(200, 200, 200);
    static Color transparentWhite = new Color(255, 255, 255, 0);
    static Color opaqueWhite = new Color(255, 255, 255, 255);
    
    PlayerController myController;
    /**
     * Creates new form PlayerInputComponent
     */
    public PlayerInputDoBetFieldComp() {
        initComponents();
        clearWarning();
    }
    
    public void set(PlayerController aController){
        myController = aController;
    }
    
    public void setInactive(){
        this.setBackground(inactiveBgColor);
        myBetBtn.setEnabled(false);
        myPassBtn.setEnabled(false);
        myBetField.setEnabled(false);
    }
    
    public void setActive(){
        this.setBackground(activeBgColor);
        myBetBtn.setEnabled(true);
        myPassBtn.setEnabled(true);
        myBetField.setEnabled(true);
    }
    
    public void setWarning(String aString){
        myInvalidInputWarningLabel.setText(aString);
        myInvalidInputWarningLabel.setForeground(opaqueWhite);
    }
    
    public void clearWarning(){
        myInvalidInputWarningLabel.setForeground(transparentWhite);
    }
    
    public void setMaxBetValue(String aString){
        myMaxBetLabelWarningValue.setText(aString);
    }
    
    private void doBet(){
        myController.playerBets(myBetField.getText());
    }
    
    private void doPass(){
        myController.playerPassFirst();
        clearWarning();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myBetLabel = new javax.swing.JLabel();
        myBetField = new javax.swing.JTextField();
        myMaxBetLabelWarning = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        myBetBtn = new javax.swing.JButton();
        myPassBtn = new javax.swing.JButton();
        myMaxBetLabelWarningValue = new javax.swing.JLabel();
        myInvalidInputWarningLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(100, 100, 100));

        myBetLabel.setForeground(new java.awt.Color(255, 255, 255));
        myBetLabel.setText("Apuesta:");

        myBetField.setText("700");
        myBetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBetFieldActionPerformed(evt);
            }
        });

        myMaxBetLabelWarning.setForeground(new java.awt.Color(255, 255, 255));
        myMaxBetLabelWarning.setText("Apuesta Maxima:");

        jSplitPane1.setBackground(new java.awt.Color(100, 100, 100));
        jSplitPane1.setDividerLocation(85);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(160, 25));

        myBetBtn.setText("Apostar");
        myBetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBetBtnActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(myBetBtn);

        myPassBtn.setText("Pasar");
        myPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPassBtnActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(myPassBtn);

        myMaxBetLabelWarningValue.setForeground(new java.awt.Color(255, 255, 255));
        myMaxBetLabelWarningValue.setText("$150");

        myInvalidInputWarningLabel.setForeground(new java.awt.Color(255, 255, 255));
        myInvalidInputWarningLabel.setText("Rango inválido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myMaxBetLabelWarning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(myMaxBetLabelWarningValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myBetLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(myBetField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(myInvalidInputWarningLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myBetLabel)
                    .addComponent(myBetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myMaxBetLabelWarning)
                    .addComponent(myMaxBetLabelWarningValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myInvalidInputWarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myBetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myBetFieldActionPerformed

    private void myPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPassBtnActionPerformed
        doPass();
    }//GEN-LAST:event_myPassBtnActionPerformed

    private void myBetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBetBtnActionPerformed
        doBet();
    }//GEN-LAST:event_myBetBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton myBetBtn;
    private javax.swing.JTextField myBetField;
    private javax.swing.JLabel myBetLabel;
    private javax.swing.JLabel myInvalidInputWarningLabel;
    private javax.swing.JLabel myMaxBetLabelWarning;
    private javax.swing.JLabel myMaxBetLabelWarningValue;
    private javax.swing.JButton myPassBtn;
    // End of variables declaration//GEN-END:variables
}
