/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI;
import poker.UI.Framework.Model;
/**
 *
 * @author MDA 174321 :)
 */
public class TextInputFieldComponent extends javax.swing.JPanel {
    private String myId;
    public String myLabel = "Label";
    public String myText = "Placeholder";
    public String myWarning = "";
    
    public TextInputFieldComponent() {
        initComponents();
        Update(null);
    }
    
    public void set(String aLabel, String aText, String aWarning){
        myLabel = aLabel;
        myText = aText;
        myWarning = aWarning;
        Update(null);
    }
    
    public TextInputFieldModel getModelData(){
        return new TextInputFieldModel( inputLabel_label.getText(),
                                        input_textField.getText(),
                                        warning_label.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputLabel_label = new javax.swing.JLabel();
        input_textField = new javax.swing.JTextField();
        warning_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        inputLabel_label.setText("Text field label");

        input_textField.setText("Text field");
        input_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_textFieldActionPerformed(evt);
            }
        });

        warning_label.setText("Warning label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warning_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel_label)
                    .addComponent(input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void input_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_textFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inputLabel_label;
    private javax.swing.JTextField input_textField;
    private javax.swing.JLabel warning_label;
    // End of variables declaration//GEN-END:variables

    public void Update(Model aModel) {
        inputLabel_label.setText(myLabel);
        input_textField.setText(myText);
        warning_label.setText(myWarning);
    }
}
