/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.UI.Framework;
import java.util.ArrayList;

/**
 *
 * @author MDA 174321 :)
 */
public abstract class View extends javax.swing.JFrame implements Updatable {
    String myId;
    Controller myController;
    ArrayList<Updatable> myComponents = new ArrayList();
  
    public View() {
        initComponents();
        instanciateController();
    }
    
    // Each View derived class should implement their own instanciateController() method because 
    // only they know what Controller derived class to implement
    public abstract void instanciateController();
    public void setController(Controller aController) {
        myController = aController;
    }
    
    public boolean UpdateComponent(String aComponentId, Model aModel){
        for(Updatable c:myComponents){
            if(c.getUpdateId().equals(aComponentId)){
                c.Update(aModel);
                return true;
            }
        }
        return false;
    }
    
    // TODO: repeated behaviour, do we need a generalization to handle lists?
    // add<SomeObject>()
    // <SomeObject>Exists()
    // get<SomeObject>ById()
    
    // Other suspect objects:
    // Component.java
    // UserModule.java
    public boolean addComponent(Updatable aComponent){
        if (aComponent != null){
            if(!componentExists(aComponent)){
                myComponents.add(aComponent);
                return true;
            }
        }
        return false;
    }
    
    public boolean componentExists(Updatable aComponent){
        return myComponents.contains(aComponent);
    }
    
    // NOTE: Inefficient search algorithm, replace myComponents with a data structure that supports better search
    // algorithms for improved efficiency
    public Updatable getComponentById (String aComponentId){
        for(Updatable u:myComponents){
            if(u.getUpdateId().equals(aComponentId)){
                return u;
            }
        }
        return null;
    }
    
    @Override
    public void Update(Model aModel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getUpdateId() {
        return myId;
    }

    @Override
    public void setUpdateId(String aId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
